# Chart values for the Camunda Platform 8 Helm chart in separate ingress setup. 
# Note: you can change the global.image.tag version value as needed.
global:
  image:
    tag: 8.5.0

  identity:
    auth:
      publicIssuerUrl: "https://keycloak.c8.dev.local/auth/realms/camunda-platform"
      connectors:
        existingSecret: #dev-identity-secrets
          name: dev-identity-secrets
      identity:
        redirectUrl: "http://identity.c8.dev.local"
      operate:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://operate.c8.dev.local"
      tasklist:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://tasklist.c8.dev.local"
      optimize:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://optimize.c8.dev.local"
      webModeler:
        redirectUrl: "https://modeler.c8.dev.local"
      console:
        existingSecret: #SetThisToMakeHelmUpgradesEasy
          name: dev-identity-secrets
        redirectUrl:  "https://console.c8.dev.local"
      zeebe:
        existingSecret: #SetThisToMakeHelmUpgradesEasy
          name: dev-identity-secrets

console:
  ## @param console.enabled if true, the Console deployment and its related resources are deployed via a helm release
  enabled: true
  image:
    pullSecrets:
      - name: dev-c8-registry
  ingress:
    enabled: true
    host: "console.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"

# Reduce Zeebe and Gateway replicas and resources to make it run locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi
 
zeebe-gateway:
  replicas: 1
#  env:
#    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
#      value: none
  ingress:
    grpc:
      enabled: true
      host: "zeebe.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"
    rest:
      enabled: true
      host: "zeebe.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"
 
operate:
  ingress:
    enabled: true
    host: "operate.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
tasklist:
  ingress:
    enabled: true
    host: "tasklist.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
optimize:
  ingress:
    enabled: true
    host: "optimize.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
identity:
  fullURL: "https://identity.c8.dev.local"
  ingress:
    enabled: true
    host: "identity.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"

identityPostgresql:
  enabled: true
  auth:
    existingSecret: dev-postgresql-secrets

identityKeycloak:
  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
  ingress:
    enabled: true
    hostname: "keycloak.c8.dev.local"
    tls: true
    extraTls:
      - secretName: dev-c8-separated
        hosts:
          - keycloak.c8.dev.local
  auth:
    existingSecret: dev-keycloak-secrets

webModeler:
  enabled: true
  image:
    pullSecrets:
      - name: dev-c8-registry
  restapi:
    mail:
      fromAddress: "no-reply@camunda.com"
    env:
      - name: ZEEBE_CA_CERTIFICATE_PATH
        value: "/home/runner/dev.c8.separated.crt"
    ##      Configuration for DEBUG logging:
    #      - name: LOGGING_LEVEL_IO_GRPC
    #        value: TRACE
    #      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
    #        value: DEBUG
    extraVolumes:
      - name: dev-c8-separated
        secret:
          secretName: dev-c8-separated
    extraVolumeMounts:
      - name: dev-c8-separated
        mountPath: "/home/runner/dev.c8.separated.crt"
        subPath: tls.crt
  webapp:
    env:
      - name: ZEEBE_CLIENT_SSL_ROOT_CERTS_PATH
        value: "/home/runner/dev.c8.separated.crt"
    extraVolumes:
      - name: dev-c8-separated
        secret:
          secretName: dev-c8-separated
    extraVolumeMounts:
      - name: dev-c8-separated
        mountPath: "/home/runner/dev.c8.separated.crt"
        subPath: tls.crt
  ingress:
    enabled: true
    webapp:
      host: "modeler.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"
    websockets:
      host: "websockets.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"

postgresql:
  enabled: true
  auth:
    password: SetThisToMakeLoginEasy
    postgresPassword: SetThisToMakeLoginEasy

connectors:
  ingress:
    enabled: true
    host: "connectors.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"

# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
  #  image: # Uncomment these lines and set a value if you want to override the default chart value.
  #    tag: 8.12.2 # Uncomment these lines and set a value if you want to override the default chart value.
  master:
    replicaCount: 1
    persistence:
      size: 8Gi