# Chart values for the Camunda Platform 8 Helm chart in combined ingress setup.
# You can change the global.image.tag version value as needed, just don't delete comment that follows it.
global:
  image:
    tag: 8.0.13

  identity:
    auth:
      publicIssuerUrl: "https://c8.dev.local/auth/realms/camunda-platform"
      operate:
        existingSecret: SetThisToMakeHelmUpgradesEasy
        redirectUrl: "https://c8.dev.local/operate"
      tasklist:
        existingSecret: SetThisToMakeHelmUpgradesEasy
        redirectUrl: "https://c8.dev.local/tasklist"
      optimize:
        existingSecret: SetThisToMakeHelmUpgradesEasy
        redirectUrl: "https://c8.dev.local/optimize"

# Reduce replicas and resources for local testing,
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 960m
      memory: 1536Mi
  pvcSize: 8Gi

zeebe-gateway:
  replicas: 1
  ingress:
    enabled: true
    host: "zeebe.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-combined"
  # Configure resources for local testing.
  # No changes needed.

operate:
  contextPath: "/operate/"
  # Reduce resources for local testing.
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

tasklist:
  contextPath: "/tasklist/"
  # Reduce resources for local testing.
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

optimize:
  contextPath: "/optimize"
  # Reduce resources for local testing.
    requests:
      cpu: 500m
      memory: 384Mi
    limits:
      cpu: 1500m
      memory: 1Gi

identity:
  fullURL: "https://c8.dev.local/identity"
  contextPath: "/identity/"
  keycloak:
    auth:
      adminPassword: SetThisToMakeLoginEasy
      managementPassword: SetThisToMakeLoginEasy
    postgresql:
      auth:
        password: SetThisToMakeLoginEasy
  # Reduce resources for local testing.
  resources:
    requests:
      cpu: 500m
      memory: 384Mi
    limits:
      cpu: 1500m
      memory: 1Gi

  ingress:
    enabled: true
    host: "c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-combined"

# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
  imageTag: 7.16.2
  replicas: 1
  minimumMasterNodes: 1
  # Allow no backup for single node setups
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    resources:
      requests:
        storage: 8Gi
  # No memory reduction
  # Elasticsearch will not run with less than 2Gi memory.
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
