# Chart values for the Camunda Platform 8 Helm chart in combined ingress setup.
# You can change the global.image.tag version value as needed, just don't delete comment that follows it.
global:
  image:
    tag: 8.2.7

  ingress:
    enabled: true
    host: "c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-combined"

  identity:
    auth:
      publicIssuerUrl: "https://c8.dev.local/auth/realms/camunda-platform"
      connectors:
        existingSecret: dev-identity-secrets
      operate:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://c8.dev.local/operate"
      tasklist:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://c8.dev.local/tasklist"
      optimize:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://c8.dev.local/optimize"
      webModeler:
        redirectUrl: "https://c8.dev.local/modeler"
      zeebe:
        existingSecret: dev-identity-secrets

# Reduce Zeebe and Gateway replicas and resources to make it run locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi

zeebe-gateway:
  replicas: 1
#  env:
#    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
#      value: none
  ingress:
    enabled: true
    host: "zeebe.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-combined"

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  contextPath: "/optimize"

identity:
  fullURL: "https://c8.dev.local/identity"
  contextPath: "/identity"
  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
    auth:
      existingSecret: dev-identity-keycloak-secrets
    postgresql:
      auth:
        existingSecret: dev-identity-keycloak-postgresql-secrets

webModeler:
#  enabled: false
  enabled: true
  image:
    tag: 8.2.1
    pullSecrets:
      - name: dev-c8-registry
  contextPath: "/modeler"
  restapi:
    mail:
      # Restapi.mail.smtpHost defines the host name of the SMTP server to be used by Web Modeler
      smtpHost: ""
      # Restapi.mail.smtpPort defines the port number of the SMTP server
      smtpPort: 587
      # Restapi.mail.smtpUser can be used to provide a user for the SMTP server
      smtpUser: ""
      # Restapi.mail.smtpPassword can be used to provide a password for the SMTP server
      smtpPassword: ""
      # Restapi.mail.smtpTlsEnabled if true, enforces TLS encryption for SMTP connections (using STARTTLS)
      smtpTlsEnabled: true
      # Restapi.mail.fromAddress defines the email address that will be displayed as the sender of emails sent by Web Modeler
      fromAddress: "no-reply@camunda.com"
      # Restapi.mail.fromName defines the name that will be displayed as the sender of emails sent by Web Modeler
      fromName: "Camunda Platform"
    env:
      - name: ZEEBE_CA_CERTIFICATE_PATH
        value: "/home/runner/dev.c8.combined.crt"
##      Configuration for DEBUG logging:
#      - name: LOGGING_LEVEL_IO_GRPC
#        value: TRACE
#      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
#        value: DEBUG
    extraVolumes:
      - name: dev-c8-combined
        secret:
          secretName: dev-c8-combined
    extraVolumeMounts:
      - name: dev-c8-combined
        mountPath: "/home/runner/dev.c8.combined.crt"
        subPath: tls.crt
  webapp:
    env:
      - name: ZEEBE_CLIENT_SSL_ROOT_CERTS_PATH
        value: "/home/runner/dev.c8.combined.crt"
    extraVolumes:
      - name: dev-c8-combined
        secret:
          secretName: dev-c8-combined
    extraVolumeMounts:
      - name: dev-c8-combined
        mountPath: "/home/runner/dev.c8.combined.crt"
        subPath: tls.crt

postgresql:
  enabled: true
  auth:
    existingSecret: dev-modeler-postgresql-secrets

connectors:
  enabled: true
  contextPath: "/connectors"

# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
  #  imageTag: 7.17.3  # Uncomment this line and set a value if you want to override the default chart value.
  replicas: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 8Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
